---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/essential-and-not-essential-genes-number-of-interactors/essential-and-not-essential-genes-number-of-interactors.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/365857/articles/486240/master/file/figures/essential-and-not-essential-genes-number-of-interactors/essential-and-not-essential-genes-number-of-interactors.png"
